### ISSUE TITLE
Need Latest guice version

### ISSUE THREAD

**Issue by vels4j** [rtatol/dropwizard-guice-jpa-eclipselink#2]
Thanks author for such contribution.

Current built throws the following error 

Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)

Need Latest guice version
<guice.version>4.1.0</guice.version>

Then it works

**Comment by rtatol** [comment]
Done.
